### ISSUE TITLE
.MAT files

### ISSUE THREAD

**Issue by sirius-cky** [JimmyChame/LSFNet#2]
Hi, the .mat file is processed into a grayscale map after getting a .mat file or a three-channel .mat file directly from a color image?
When getting the h5py file of the train dataset, the following error appears when running the gen_deatset.py:
    meta['WhiteLevel'] = [metadata['meta']['saturation'][0][0][0][0]]
KeyError: 'meta'
 So consider whether the .mat file and the data in the dictionary do not correspond?
thanks！

**Comment by JimmyChame** [comment]
The MAT files store some header information which extracted from the raw images in DNG format. You could refer to this code:
[https://github.com/JimmyChame/LSFNet/blob/master/Dataset/read_all_meta.m](https://github.com/JimmyChame/LSFNet/blob/master/Dataset/read_all_meta.m)

**Comment by sirius-cky** [comment]
Thank you! After getting the .mat file through this file, I have already started training the neural network.By the way, could you please tell me how long your training process took? And how many RTX 1080Ti were used in your training process？

**Comment by JimmyChame** [comment]
Maybe a dozen hours for two RTX 1080Ti.
